name: 'Deploy lambda function'
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: "Lambda deploy"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}

            - name: Set up Node
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install npm packages
              run: |
                npm install

            - name: Deploy Code
              run: |
                zip -j deploy.zip ./*
                aws lambda update-function-code --function-name=customer_auth --zip-file=fileb://deploy.zip 